// MODIFICA ESTA URL POR LA DEL SERVICIO WEB DESPUES DE HABERLO DESPLEGADO
const AS_URL_BASE = "https://script.google.com/a/~/macros/s/AKfycbxUSz7C7pH4Y_QGT-p2dZRzYpTShyQn6AK46FFTFiiea7rHkSHo6J5UL5DdAXCOdEp63w/exec";
